# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 892211105d35628a6c4793b2c6344915ae0c577efb12ac5cf401b7ea01bff1f09b6ab67e35e662c94540e49e22947627e47e8850dcadcc2fd4fdc7569a41fdc7

test:
  secret_key_base: bc75f7343d34b1bfd6b6066df6ca5855abd4e08149dd9a444900c5491980bd48195fadc0e6599231306ce4e9486e6f2db2d0209d5e23c1504101877c9279b07e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
